name: github pages

on:
  push:
    branches:
      - main # default branch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: haianweifeng
          user_email: 1531297152@qq.com
          github_token: ${{ secrets.ACCESS_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
