name: github pages

on:
  push:
    branches:
      - main # default branch


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      env:
          MY_EMAIL: 1531297152@qq.com
          MY_NAME: haianweifeng
      - uses: actions/checkout@v3
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/haianweifeng/react-customize-data-table.git
      - run: npm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
