name: github pages

on:
  push:
    branches:
      - main # default branch


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
        git config --global user.email 1531297152@qq.com
        git config --global user.name haianweifeng
        git remote set-url origin https://1531297152@qq.com:${{ secrets.GITHUB_TOKEN }}@github.com/haianweifeng/react-customize-data-table.git
        npm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
